[project]
name = "subtransllm"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.57.1",
    "click>=8.2.1",
    "openai>=1.95.0",
    "python-dotenv>=1.1.1",
    "requests>=2.32.4",
]
